### ISSUE TITLE
Arx Fatalis (1700) - Working Package

### ISSUE THREAD

**Issue by d10sfan** [dreamer/luxtorpeda#3]
This repo adds support for Arx Fatalis: https://gitlab.com/d10sfan/luxtorpeda-arxlibertatis

The packages.json for this game looks like the following:

```
        "1700": {
		"game_name":    "Arx Fatalis",
		"package":      "dist.tar.xz",
		"command":      "./arx"
	}
```

For the boost library, I had to use this to get it to download all the sub-modules: git submodule update --init --recursive. Not sure how the gitlab ci tool will handle that portion.

One note with the way this game works is that the engine wants to do a install process for the first load. I didn't try to change any of the startup behavior, so if you start it for the first time, you'll see an interactive GUI for copying and fixing the files from the steam installation to arx's directory (in my system's case it was ~/.local/share/arx). It finds the steam directory, so it's pretty easy. Once it's done, you can launch the game again and then everything will work as expected. All of this is done through launching the game through steam, so it's pretty seamless.

**Comment by dreamer** [comment]
I took a brief look and this one is a little bit weird - Data repo in Arx project contains only icons (perhaps they were preparing for more content, which was never needed in the end), so it can be included using git-subtree (or just dump) instead of submodule; and I think boost will be used by more games in the future, so I probably need to mirror it as well.

This one requires some more work on my side, WIP.

**Comment by d10sfan** [comment]
Closed with PR 14
