### ISSUE TITLE
Engine request - SCUMMVM

### ISSUE THREAD

**Issue by neuromancer** [dreamer/luxtorpeda#9]
SCUMMVM added a ton of games recently: https://www.scummvm.org/compatibility/

**Comment by mindcombatant** [comment]
Agreed, this should be a thing, but it may need to be another sister project, like Boxtron. Also, putting this in this same issue, as it's very related, but ResidualVM would be nice to have as well. I could break that request off to a separate issue if you'd prefer, though, just lemmee know

**Comment by dreamer** [comment]
Yes, we discussed it in the past on Discord channel https://discord.gg/8mFhUPX and consensus was: making it a separate tool makes the most sense.

Some games can be run through DOSBox or ScummVM or native port - and each option will have its pros and cons. Implementing this choice inside Luxtorpeda would be less user friendly than letting user choose compatibility tool using Steam GUI.

I can kickstart the project - 90% of Boxtron code could be simply reused, but most development effort will go into Luxtorpeda tool in the immediate future.

(waiting for ideas for a name - so far "Scummstron" was floating inside mine ;))

**Comment by mindcombatant** [comment]
Names, huh? Hmm... Maybe, if doing both ScummVM and ResidualVM, "Adventuretron" as a name, because all the games that both those support are classic adventure games. or, something along those lines. I'm personally not fond of reusing the "tron" suffix (it's already not used in both the current projects, why make it a standard suffix now?), but it's not exactly my project, so... Anyway, just a suggestion, dunno if it's even really a strong one, but meh. I may join the discord to brainstorm further.

**Comment by dreamer** [comment]
Pre-release, initial version of new tool was pushed to https://github.com/dreamer/roberta It is very limited now, but in few days it should be able to handle most games ScummVM can play.

**Comment by dreamer** [comment]
Roberta v0.1.0 was just released: https://github.com/dreamer/roberta :)

Future issues regarding ScummVM/ResidualVM please submit to that project.

**Comment by mindcombatant** [comment]
great name choice! thanks!
